language: node_js
node_js:
  - "18"
sudo: false

script:
  - echo 'Installing Dependencies'
  - npm install
  - echo 'Running tests'
  - npm run test

branches:
  only:
    - master

cache:
  directories:
    - node_modules

deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api-key: d0680e56-6c41-46c7-9ee3-5ed76c544dc3
  app: socialnetwrokapi
