language: node_js
node_js:
  - "10"
sudo: false

branches:
  only:
    - master

cache:
  directories:
    - node_modules

deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api-key: d0680e56-6c41-46c7-9ee3-5ed76c544dc3
  app: your_heroku_app_name
